'use strict';

export const CREATE_NEW_INVOICE = 'CREATE_NEW_INVOICE';
export const DELETE_INVOICE = 'DELETE_INVOICE';
export const REMOVE_EMPTY_INVOICES = 'REMOVE_EMPTY_INVOICES';
export const SELECT_INVOICE = 'SELECT_INVOICE';
export const UPDATE_INVOICE = 'UPDATE_INVOICE';
export const UPDATE_LINE_ITEM = 'UPDATE_LINE_ITEM';
export const ADD_LINE_ITEM = 'ADD_LINE_ITEM';
export const REMOVE_LINE_ITEM = 'REMOVE_LINE_ITEM';

